import { DaozhangRecord, NeibanRecord, Note, TreasureItem, ExpeditionRecord } from './types';

// 预设经典刀剑范本（可供用户在需要时自愿点击“载入经典刀剑范本”引入，默认不强行预置）
export const CLASSIC_PRESET_SWORDS: DaozhangRecord[] = [
  {
    id: 'dz-003',
    number: 'No.003',
    name: '三日月宗近',
    swordType: '太刀',
    school: '三条',
    date: '2026-01-15',
    notes: '平安时代永延年间的刀工三条宗近所作。天下五剑之一，被誉为最美之刃。刃纹上有许多新月形状的「打除」，故得此名。',
    favorite: true,
  },
  {
    id: 'dz-005',
    number: 'No.005',
    name: '小狐丸',
    swordType: '太刀',
    school: '三条',
    date: '2026-02-02',
    notes: '传说为三条宗近得稻荷明神派遣的神狐相助合力锻造的名刃。举止优雅自称「小狐」，野性与神圣兼具。',
  },
  {
    id: 'dz-007',
    number: 'No.007',
    name: '石切丸',
    swordType: '大太刀',
    school: '三条',
    date: '2026-02-14',
    notes: '三条宗近所作大太刀，供奉于石切剑箭神社。长年作为祛除肿瘤、驱散祸患的神刀受人参拜，性情温厚慈爱。',
  },
  {
    id: 'dz-025',
    number: 'No.025',
    name: '一期一振',
    swordType: '太刀',
    school: '粟田口',
    date: '2026-02-28',
    notes: '粟田口吉光一生中仅锻造过的一柄太刀，故名一期一振。丰臣秀吉之爱刀，粟田口短刀与胁差的温柔长兄。',
    favorite: true,
  },
  {
    id: 'dz-031',
    number: 'No.031',
    name: '乱藤四郎',
    swordType: '短刀',
    school: '粟田口',
    date: '2026-01-18',
    notes: '粟田口吉光所锻短刀中少有的乱刃纹。外表宛若金发少女，内心却极具男子气概。',
  },
  {
    id: 'dz-055',
    number: 'No.055',
    name: '莺丸',
    swordType: '太刀',
    school: '古备前',
    date: '2026-03-01',
    notes: '古备前派友成所作的名刃。悠闲自得，喜爱饮茶，对同乡的大包平十分挂心。',
  },
  {
    id: 'dz-079',
    number: 'No.079',
    name: '宗三左文字',
    swordType: '打刀',
    school: '左文字',
    date: '2026-01-20',
    notes: '三好宗三献给武田信虎，后转入今川义元、织田信长之手。被称为「夺取天下之刀」，刻有信长的魔王之铭。',
  },
  {
    id: 'dz-083',
    number: 'No.083',
    name: '江雪左文字',
    swordType: '太刀',
    school: '左文字',
    date: '2026-03-05',
    notes: '筑前左文字作，板部冈江雪斋所持。厌恶战斗与流血，时刻祈愿世间和平。',
  },
  {
    id: 'dz-085',
    number: 'No.085',
    name: '加州清光',
    swordType: '打刀',
    school: '非左（加州）',
    date: '2026-01-01',
    notes: '新选组冲田总司所持爱刀。注重打扮与涂抹指甲油，希望能得到主公长长久久的宠爱。',
    favorite: true,
  },
  {
    id: 'dz-087',
    number: 'No.087',
    name: '大和守安定',
    swordType: '打刀',
    school: '大和守',
    date: '2026-01-08',
    notes: '同样曾侍奉新选组冲田总司。平日温和沉静，出战时会展露出犀利悍勇的一面。',
  },
  {
    id: 'dz-095',
    number: 'No.095',
    name: '山姥切国广',
    swordType: '打刀',
    school: '堀川',
    date: '2026-01-02',
    notes: '安土桃山时代著名刀工堀川国广的杰作。虽然是仿作，却拥有卓越的实力与清丽的美貌，因自卑常用白布裹身。',
    bondLevel: 4,
    memoEntries: [
      {
        id: 'memo-1',
        date: '2026-09-28',
        category: '互动小记',
        content: '主殿递上清洗晾干的新白布时，虽然嘴上嘟囔着“不需要这么费心……”，但耳根泛红地接过去裹得紧紧的，眼神格外温和。',
      },
      {
        id: 'memo-2',
        date: '2026-09-24',
        category: '刀装心得',
        content: '与山姥切一同配制精锐弓兵刀装，他精准挑选了上等玉钢，神情专注沉稳。言道：“只要装备精良，即便面对强敌亦绝不后退。”',
      },
      {
        id: 'memo-3',
        date: '2026-09-20',
        category: '问答签文',
        content: '晨间摇得大吉签文，山姥切低语：“……吉兆吗。如果主殿相信的话，今天就依仗这份武运好好挥刀吧。”',
      },
    ],
  },
  {
    id: 'dz-118',
    number: 'No.118',
    name: '压切长谷部',
    swordType: '打刀',
    school: '长谷部',
    date: '2026-01-10',
    notes: '长谷部国重所作，织田信长曾用其将躲在茶架下的茶坊主连同茶架一刀切断，忠心耿耿，为主公万死不辞。',
    favorite: true,
  },
  {
    id: 'dz-130',
    number: 'No.130',
    name: '鹤丸国永',
    swordType: '太刀',
    school: '五条',
    date: '2026-02-20',
    notes: '平安时代五条国永所作。通体雪白如仙鹤，性格却喜爱制造惊吓，认为人生若无惊喜便与死人无异。',
    favorite: true,
  },
  {
    id: 'dz-134',
    number: 'No.134',
    name: '烛台切光忠',
    swordType: '太刀',
    school: '备前长船',
    date: '2026-01-12',
    notes: '备前长船派始祖光忠所作。伊达政宗斩杀近侍时连同青铜烛台一并削断。注重仪容帅气，擅长本丸厨艺。',
  },
];

// 系统初始刀账：默认纯净为空，由审神者亲自登用显现
export const INITIAL_PRESET_SWORDS: DaozhangRecord[] = [];

export const INITIAL_NOTES: Note[] = [
  {
    id: 'note-1',
    content: '今日初春本丸樱花初绽，与近侍一同清点本丸府库。锻刀房炉火未歇，愿武运长久。',
    date: '2026/09/25 10:15',
    tag: '日常',
  },
  {
    id: 'note-2',
    content: '派遣第二部队前往「鸟羽伏见」出征，途中击溃敌方检非违使，全员轻伤胜利归阵。',
    date: '2026/09/24 16:30',
    tag: '出征',
  },
  {
    id: 'note-3',
    content: '今日马当番交由长谷部与清光照料，战马神骏饱餐粮草。手合场由一期一振与鹤丸对阵切磋。',
    date: '2026/09/23 14:00',
    tag: '内番',
  },
  {
    id: 'note-4',
    content: '投入砥石与冷却材各50，锻出特上精锐骑兵与重步兵各三套，运势极佳。',
    date: '2026/09/22 09:20',
    tag: '刀装',
  },
];

// 经典内番范本示例数据（供审神者需要时自愿载入参考，默认不强行预置）
export const CLASSIC_PRESET_NEIBAN: NeibanRecord[] = [
  {
    id: 1727251200001,
    date: '2026-09-25',
    name: '压切长谷部',
    type: '马当番',
    done: true,
    progress: 100,
    status: 'completed',
  },
  {
    id: 1727251200002,
    date: '2026-09-25',
    name: '加州清光',
    type: '畑当番',
    done: false,
    progress: 50,
    status: 'half',
    escapeReason: '锄地半途怕弄脏新涂的朱红指甲油，回廊下歇息喝茶',
  },
  {
    id: 1727251200003,
    date: '2026-09-24',
    name: '三日月宗近',
    type: '寝当番',
    done: true,
    progress: 100,
    status: 'completed',
  },
  {
    id: 1727251200004,
    date: '2026-09-24',
    name: '鹤丸国永',
    type: '畑当番',
    done: false,
    progress: 0,
    status: 'escaped',
    escapeReason: '借口给田鼠挖陷阱制造惊喜，悄悄溜至万屋买甘味去了',
  },
  {
    id: 1727251200005,
    date: '2026-09-24',
    name: '山姥切国广',
    type: '手合场',
    done: true,
    progress: 100,
    status: 'completed',
  },
];

// 系统初始内番当值名册：默认纯净为空，等待审神者亲自安排当值
export const INITIAL_NEIBAN: NeibanRecord[] = [];

// 系统初始宝物库：默认纯净为空
export const INITIAL_PRESET_TREASURES: TreasureItem[] = [];

// 系统初始周度手札 (Weekly Planner) 经典范本
export const INITIAL_WEEKLY_PLANNER = {
  id: 'current-week',
  year: 2026,
  monthIndex: 12,
  weekIndex: 4,
  goalMemo: '每周定好目标，一周后确认是否达成。\n用 habit tracker 来提高做事效率，\n计划每日必做的事情。',
  days: {
    mon: [
      { id: 'm1', text: '准时出阵与演练', done: true },
      { id: 'm2', text: '本丸回廊整理', done: false },
      { id: 'm3', text: '完成手帐随笔', done: false },
      { id: 'm4', text: '刀装锻造研习', done: false },
      { id: 'm5', text: '运动 30 min', done: false },
    ],
    tue: [
      { id: 't1', text: '马当番照料', done: false },
      { id: 't2', text: '寝室整理与通风', done: false },
      { id: 't3', text: '去万屋采买点心', done: false },
      { id: 't4', text: '背 50 个词汇', done: false },
      { id: 't5', text: '运动 30 min', done: false },
    ],
    wed: [
      { id: 'w1', text: '准时就寝不熬夜', done: false },
      { id: 'w2', text: '完成周中汇报', done: false },
      { id: 'w3', text: '给近侍挑选景趣', done: false },
      { id: 'w4', text: '运动 30 min', done: false },
    ],
    thu: [
      { id: 'th1', text: '准时出阵', done: false },
      { id: 'th2', text: '畑当番蔬菜采收', done: false },
      { id: 'th3', text: '阅读 30 min', done: false },
      { id: 'th4', text: '整理刀账番号', done: false },
    ],
    fri: [
      { id: 'f1', text: '背 50 个词汇', done: false },
      { id: 'f2', text: '运动 30 min', done: false },
      { id: 'f3', text: '周末行程提前安排', done: true },
      { id: 'f4', text: '和同僚战友小聚', done: false },
    ],
    sat: [
      { id: 'sa1', text: '连队战冲刺御岁魂', done: false },
      { id: 'sa2', text: '给爱刀拍摄宝物立拍得', done: false },
      { id: 'sa3', text: '现世大采购', done: false },
    ],
    sun: [
      { id: 'su1', text: '复盘本周周度目标达成', done: false },
      { id: 'su2', text: '制定下周目标', done: false },
      { id: 'su3', text: '早睡养精蓄锐', done: false },
    ],
  },
  todoStickyNotes: '12.21  逛街买谷\n12.25  现世聚会\n12.27  连队战十万魂冲刺',
};

// 预设远征战报示例清单
export const INITIAL_EXPEDITIONS: ExpeditionRecord[] = [
  {
    id: 'exp-1',
    date: '2026-10-01',
    area: '时代1-1 鸟羽出阵',
    fleet: '第二部队',
    result: '大成功',
    charcoal: 150,
    steel: 150,
    coolant: 0,
    whetstone: 0,
    charcoalExpense: 20,
    steelExpense: 10,
    coolantExpense: 0,
    whetstoneExpense: 0,
    itemsEarned: '小判箱(中) x1',
    notes: '全员飘樱花满状态大成功回港',
  },
  {
    id: 'exp-2',
    date: '2026-10-02',
    area: '时代1-2 会津侦察',
    fleet: '第二部队',
    result: '成功',
    charcoal: 100,
    steel: 0,
    coolant: 120,
    whetstone: 0,
    charcoalExpense: 15,
    steelExpense: 0,
    coolantExpense: 10,
    whetstoneExpense: 0,
    itemsEarned: '手入札 x1',
    notes: '顺利完成侦察，微量手入消耗',
  },
  {
    id: 'exp-3',
    date: '2026-10-03',
    area: '时代2-1 江户迎击',
    fleet: '第三部队',
    result: '大成功',
    charcoal: 180,
    steel: 180,
    coolant: 180,
    whetstone: 180,
    charcoalExpense: 30,
    steelExpense: 25,
    coolantExpense: 20,
    whetstoneExpense: 15,
    itemsEarned: '小判箱(大) x1, 委托札 x1',
    notes: '斩获四项平衡大资源',
  },
  {
    id: 'exp-4',
    date: '2026-10-04',
    area: 'B-1 公武合体运动',
    fleet: '第二部队',
    result: '成功',
    charcoal: 220,
    steel: 260,
    coolant: 150,
    whetstone: 0,
    charcoalExpense: 35,
    steelExpense: 30,
    coolantExpense: 15,
    whetstoneExpense: 0,
    itemsEarned: '加速札 x1',
    notes: '长途远征平安凯旋',
  },
  {
    id: 'exp-5',
    date: '2026-10-05',
    area: '时代3-1 织田安土',
    fleet: '第三部队',
    result: '大成功',
    charcoal: 250,
    steel: 200,
    coolant: 220,
    whetstone: 240,
    charcoalExpense: 40,
    steelExpense: 30,
    coolantExpense: 25,
    whetstoneExpense: 20,
    itemsEarned: '小判箱(特大) x1',
    notes: '队长加州清光凯旋，战果极其丰硕',
  },
];


